format_version: 2
environments:
  pre-qa:
    pipelines:
      - sample-node-js
pipelines:
  iwf-backend-build-yaml:
    group: node-js-pipeline
    lock_behavior: unlockWhenFinished
    environment_variables:
      PROJECT_ID: demo
    materials:
      node-js:
        git: git@github.com:stellawi/demo-node-js.git
    stages:
      - pre-deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            get-zip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - echo "pre-deploy"
      - deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            unzip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - echo "unzip"
                    - echo "sample-nodejs:${GO_PIPELINE_LABEL}" >  sample-nodejs-version.txt
              artifacts:
                - build:
                    source: sample-nodejs-version.txt
                    destination: nodejs-version/                    
      - post-deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            unzip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - echo "post-deploy"