format_version: 2
environments:
  pre-qa:
    pipelines:
      - sample-node-js
pipelines:
  sample-node-js:
    group: node-js-pipeline
    lock_behavior: unlockWhenFinished
    environment_variables:
      PROJECT_ID: demo
    materials:
      nodejs:
        git: https://github.com/stellawi/demo-node-js.git
      config:
        git: https://github.com/stellawi/gocd-file-configuration.git
    stages:
      - verify:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            get-zip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - ./pre-deploy.sh
      - pre-deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            get-zip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - ./pre-deploy.sh
      - deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            unzip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - ./deploy.sh
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - echo "sample-nodejs:${GO_PIPELINE_LABEL}" > sample-nodejs-version.txt
              artifacts:
                - build:
                    source: sample-nodejs-version.txt
                    destination: nodejs-version/                    
      - post-deploy:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          jobs:
            unzip:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: bash
                    arguments:
                    - -cl
                    - ./post-deploy.sh